package view;

import customModels.QLChucVu;
import customModels.QLNhanVien;
import customModels.QLTaiKhoan;
import domainModels.ChucVu;
import domainModels.NhanVien;
import java.awt.Image;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.IchucVuService;
import service.InhanVienService;
import service.ItaiKhoanService;
import service.chucVuService;
import service.nhanVienService;
import service.taiKhoanService;

/**
 *
 * @author thanh
 */
public final class QuanLy extends javax.swing.JPanel {

    private final InhanVienService _InhanVienService;
    private final IchucVuService _IchucVuService;
    private final ItaiKhoanService _ItaiKhoanService;
    DefaultTableModel tblModel = new DefaultTableModel();
    int select = -1;
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-mm-dd");

    /**
     * Creates new form NewJPanel
     */
    public QuanLy() {
        initComponents();
        _InhanVienService = new nhanVienService();
        _IchucVuService = new chucVuService();
        _ItaiKhoanService = new taiKhoanService();
        filltoTableNhanVien();
        filltoTableChucVu();
        filltoTableTaiKhoan();
        txtNgayLap.setEnabled(false);
    }
// Xử Lý Logic Form NhanVien

    public void filltoTableNhanVien() {
        List<QLNhanVien> listNhanVien = _InhanVienService.getListNhanVien();
        tblModel = (DefaultTableModel) tblNhanVien.getModel();
        tblModel.setRowCount(0);
        cboNhanVien.removeAllItems();
        for (QLNhanVien nv : listNhanVien) {
            Object[] data = {
                nv.getMaNV(),
                nv.getTenNV(),
                nv.getGioiTinhNV() ? "Nam" : "Nữ",
                nv.getNgaySinhNV(),
                nv.getDiaChiNV(),
                nv.getSdtNV(),
                nv.getImage()};
            tblModel.addRow(data);
            cboNhanVien.addItem(nv.getTenNV());
        }
    }

    public void clearFormNhanVien() {
        select = -1;
        txtMaNV.setText("");
        txtTenNV.setText("");
        buttonGroup1.clearSelection();
        txtNgaySinhNV.setDate(null);
        txtDiaChiNV.setText("");
        txtSoDT.setText("");
        lblImage.setText("");
        lblImage.setIcon(null);
        txtMaNV.setEnabled(true);
    }

    public void filltoTableChucVu() {
        List<QLChucVu> listChucVu = _IchucVuService.getListChucVu();
        tblModel = (DefaultTableModel) tblChucVu.getModel();
        tblModel.setRowCount(0);
        cboChucVu.removeAllItems();
        for (QLChucVu cv : listChucVu) {
            Object[] data = {
                cv.getMaChucVu(),
                cv.getTenChucVu(),
                cv.getMoTa()};
            tblModel.addRow(data);
            cboChucVu.addItem(cv.getTenChucVu());
        }
    }

    public void clearFormChucVu() {
        txtMaChucVu.setText("");
        txtTenChucVu.setText("");
        txtMoTa.setText("");
        txtMaChucVu.setEnabled(true);
    }

    // Xử Lý Logic Form NhanVien
    public void filltoTableTaiKhoan() {
        List<QLTaiKhoan> listTaiKhoan = _ItaiKhoanService.getListTaiKhoan();
        tblModel = (DefaultTableModel) tblTaiKhoan.getModel();
        tblModel.setRowCount(0);
        for (QLTaiKhoan tk : listTaiKhoan) {
            Object[] data = {
                tk.getNhanVien().getMaNV(),
                tk.getChucVu().getMaChucVu(),
                tk.getTenTK(),
                tk.getMatKhau(),
                tk.getNgayLap()};
            tblModel.addRow(data);
        }
    }

    public void clearFormTaiKhoan() {
        select = -1;
        txtTenTK.setText("");
        txtMatKhau.setText("");
        txtNgayLap.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        NHANVIEN = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        txtMaNV = new javax.swing.JTextField();
        lblMaNV = new javax.swing.JLabel();
        lblTenNV = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        lblGioiTinh = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        lblNgaySinhNV = new javax.swing.JLabel();
        lblDiaChiNV = new javax.swing.JLabel();
        txtDiaChiNV = new javax.swing.JTextField();
        lblSoDT = new javax.swing.JLabel();
        txtSoDT = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnFindNhanVien = new javax.swing.JButton();
        btnDeleteNhanVien = new javax.swing.JButton();
        btnSaveNhanVien = new javax.swing.JButton();
        btnUpdateNhanVien = new javax.swing.JButton();
        btnClearNhanVien = new javax.swing.JButton();
        txtNgaySinhNV = new com.toedter.calendar.JDateChooser();
        txtTimKiem = new javax.swing.JTextField();
        btnOderByMaNV = new javax.swing.JButton();
        btnOderByName = new javax.swing.JButton();
        btnOderByDiaChi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        lblMaChucVu = new javax.swing.JLabel();
        txtMaChucVu = new javax.swing.JTextField();
        lblTenChucVu = new javax.swing.JLabel();
        txtTenChucVu = new javax.swing.JTextField();
        lblMoTa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        btnThemChucVu = new javax.swing.JButton();
        btnUpdateChucVu = new javax.swing.JButton();
        btnDeleteChucVu = new javax.swing.JButton();
        btnClearChucVu = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblChucVu = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        lblMaNVTK = new javax.swing.JLabel();
        cboNhanVien = new javax.swing.JComboBox<>();
        lblMaCVTK = new javax.swing.JLabel();
        cboChucVu = new javax.swing.JComboBox<>();
        lblTenTK = new javax.swing.JLabel();
        txtTenTK = new javax.swing.JTextField();
        lblMatKhau = new javax.swing.JLabel();
        btnThemTK = new javax.swing.JButton();
        btnSuaTK = new javax.swing.JButton();
        btnXoaTK = new javax.swing.JButton();
        btnCleardTk = new javax.swing.JButton();
        btnTimKiemTK = new javax.swing.JButton();
        J = new javax.swing.JScrollPane();
        tblTaiKhoan = new javax.swing.JTable();
        txtMatKhau = new javax.swing.JPasswordField();
        lblNgayLap = new javax.swing.JLabel();
        txtNgayLap = new javax.swing.JTextField();

        lblMaNV.setText("Mã Nhân Viên");

        lblTenNV.setText("Tên Nhân Viên");

        lblGioiTinh.setText("Giới Tính");

        buttonGroup1.add(rdoNam);
        rdoNam.setText("Nam");

        buttonGroup1.add(rdoNu);
        rdoNu.setText("Nữ ");

        lblNgaySinhNV.setText("Ngày Sinh");

        lblDiaChiNV.setText("Địa Chỉ");

        lblSoDT.setText("Số Điện Thoại");

        lblImage.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        lblImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên", "Tên Nhân Viên", "Giới Tính", "Ngày Sinh", "Địa Chỉ", "Số Điện Thoại", "Ảnh"
            }
        ));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblNhanVien);

        btnFindNhanVien.setText("TÌM KIẾM");
        btnFindNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindNhanVienActionPerformed(evt);
            }
        });

        btnDeleteNhanVien.setText("XÓA");
        btnDeleteNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteNhanVienActionPerformed(evt);
            }
        });

        btnSaveNhanVien.setText("THÊM");
        btnSaveNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveNhanVienActionPerformed(evt);
            }
        });

        btnUpdateNhanVien.setText("SỬA");
        btnUpdateNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateNhanVienActionPerformed(evt);
            }
        });

        btnClearNhanVien.setText("CLEAR");
        btnClearNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnDeleteNhanVien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClearNhanVien))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnSaveNhanVien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btnUpdateNhanVien))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(btnFindNhanVien)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveNhanVien)
                    .addComponent(btnUpdateNhanVien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClearNhanVien, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDeleteNhanVien, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(30, 30, 30)
                .addComponent(btnFindNhanVien))
        );

        txtNgaySinhNV.setDateFormatString("dd-M-y");

        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        btnOderByMaNV.setText("Sắp Xếp Theo Mã Nhân Viên");
        btnOderByMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOderByMaNVActionPerformed(evt);
            }
        });

        btnOderByName.setText("Sắp Xếp Theo Tên Nhân Viên");
        btnOderByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOderByNameActionPerformed(evt);
            }
        });

        btnOderByDiaChi.setText("Sắp Xếp Theo Địa Chỉ Nhân Viên");
        btnOderByDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOderByDiaChiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnOderByMaNV)
                        .addGap(152, 152, 152)
                        .addComponent(btnOderByName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOderByDiaChi))
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMaNV)
                                    .addComponent(lblTenNV))
                                .addGap(63, 63, 63)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rdoNam)
                                        .addGap(60, 60, 60)
                                        .addComponent(rdoNu))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTenNV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGioiTinh)
                                    .addComponent(lblDiaChiNV)
                                    .addComponent(lblSoDT)
                                    .addComponent(lblNgaySinhNV))
                                .addGap(68, 68, 68)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                    .addComponent(txtDiaChiNV)
                                    .addComponent(txtSoDT, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                    .addComponent(txtNgaySinhNV, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(160, 160, 160)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaNV)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTenNV)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGioiTinh)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rdoNam)
                                .addComponent(rdoNu))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNgaySinhNV)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNgaySinhNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDiaChiNV)
                                    .addComponent(txtDiaChiNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSoDT)
                                    .addComponent(txtSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOderByMaNV)
                    .addComponent(btnOderByName)
                    .addComponent(btnOderByDiaChi))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        NHANVIEN.setViewportView(jPanel1);

        jTabbedPane1.addTab("NHÂN VIÊN", NHANVIEN);

        lblMaChucVu.setText("Mã Chức Vụ");

        lblTenChucVu.setText("Tên Chức Vụ");

        lblMoTa.setText("Mô Tả");

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane1.setViewportView(txtMoTa);

        btnThemChucVu.setText("THÊM");
        btnThemChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemChucVuActionPerformed(evt);
            }
        });

        btnUpdateChucVu.setText("SỬA");
        btnUpdateChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateChucVuActionPerformed(evt);
            }
        });

        btnDeleteChucVu.setText("XÓA");
        btnDeleteChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteChucVuActionPerformed(evt);
            }
        });

        btnClearChucVu.setText("CLEAR");
        btnClearChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearChucVuActionPerformed(evt);
            }
        });

        tblChucVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "MÃ CHỨC VỤ", "TÊN CHỨC VỤ", "MÔ TẢ"
            }
        ));
        tblChucVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChucVuMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblChucVu);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaChucVu)
                            .addComponent(lblTenChucVu)
                            .addComponent(lblMoTa))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnThemChucVu)
                                .addGap(80, 80, 80)
                                .addComponent(btnUpdateChucVu)
                                .addGap(80, 80, 80)
                                .addComponent(btnDeleteChucVu)
                                .addGap(80, 80, 80)
                                .addComponent(btnClearChucVu))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                            .addComponent(txtTenChucVu)
                            .addComponent(txtMaChucVu)))
                    .addComponent(jScrollPane5))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaChucVu)
                    .addComponent(txtMaChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTenChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenChucVu))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMoTa)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemChucVu)
                    .addComponent(btnUpdateChucVu)
                    .addComponent(btnDeleteChucVu)
                    .addComponent(btnClearChucVu))
                .addGap(60, 60, 60)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel4);

        jTabbedPane1.addTab("CHỨC VỤ", jScrollPane2);

        lblMaNVTK.setText("Tên Nhân viên");

        lblMaCVTK.setText("CHỨC VỤ");

        lblTenTK.setText("Tên tài khoản");

        lblMatKhau.setText("Mật khẩu");

        btnThemTK.setText("THÊM");
        btnThemTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTKActionPerformed(evt);
            }
        });

        btnSuaTK.setText("SỬA");
        btnSuaTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaTKActionPerformed(evt);
            }
        });

        btnXoaTK.setText("XÓA");
        btnXoaTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTKActionPerformed(evt);
            }
        });

        btnCleardTk.setText("CLEAR");
        btnCleardTk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleardTkActionPerformed(evt);
            }
        });

        btnTimKiemTK.setText("TÌM KIẾM");
        btnTimKiemTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemTKActionPerformed(evt);
            }
        });

        tblTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MÃ NHÂN VIÊN", "MÃ CHỨC VỤ", "TÊN TÀI KHOẢN", "MẬT KHẨU", "NGÀY TẠO"
            }
        ));
        tblTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTaiKhoanMouseClicked(evt);
            }
        });
        J.setViewportView(tblTaiKhoan);

        lblNgayLap.setText("Ngày Lập");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(J, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMatKhau)
                            .addComponent(lblTenTK)
                            .addComponent(lblMaNVTK)
                            .addComponent(lblNgayLap))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnThemTK)
                                .addGap(60, 60, 60)
                                .addComponent(btnSuaTK)
                                .addGap(60, 60, 60)
                                .addComponent(btnXoaTK)
                                .addGap(60, 60, 60)
                                .addComponent(btnCleardTk)
                                .addGap(60, 60, 60)
                                .addComponent(btnTimKiemTK))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(cboNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(lblMaCVTK)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                .addComponent(cboChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTenTK)
                            .addComponent(txtMatKhau)
                            .addComponent(txtNgayLap))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaNVTK)
                    .addComponent(cboNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaCVTK)
                    .addComponent(cboChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenTK)
                    .addComponent(txtTenTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatKhau)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNgayLap)
                    .addComponent(txtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemTK)
                    .addComponent(btnSuaTK)
                    .addComponent(btnXoaTK)
                    .addComponent(btnCleardTk)
                    .addComponent(btnTimKiemTK))
                .addGap(60, 60, 60)
                .addComponent(J, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel5);

        jTabbedPane1.addTab("TÀI KHOẢN", jScrollPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1013, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImageMouseClicked
        JFileChooser fileChooser = new JFileChooser("D:\\SOF203\\JAVA 3\\IMAGES");

        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            // Khởi tạo file với giá trị = file đã chọn ở khung chọn file
            File selectedFile = fileChooser.getSelectedFile();
            // Lấy kích thước khung ảnh
            int imgW = lblImage.getWidth();
            int imgH = lblImage.getHeight();
            ImageIcon icon = new ImageIcon(new ImageIcon(selectedFile.getAbsolutePath()).getImage().getScaledInstance(imgW, imgH, Image.SCALE_DEFAULT));
            lblImage.setName(selectedFile.getAbsolutePath());
            lblImage.setIcon(icon);
            lblImage.setHorizontalAlignment(JLabel.CENTER);
            lblImage.setVerticalAlignment(JLabel.CENTER);
            System.out.println("Selected file: " + selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_lblImageMouseClicked

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        // TODO add your handling code here:
        int row = tblNhanVien.getSelectedRow();

        String maNV = tblNhanVien.getValueAt(row, 0).toString();
        String tenNV = tblNhanVien.getValueAt(row, 1).toString();
        String gioiTinhNV = tblNhanVien.getValueAt(row, 2).toString();
        String ngaySinhNV = tblNhanVien.getValueAt(row, 3).toString();
        String diaChiNV = tblNhanVien.getValueAt(row, 4).toString();
        String soDtNV = tblNhanVien.getValueAt(row, 5).toString();
        String image = tblNhanVien.getValueAt(row, 6).toString();

        txtMaNV.setEnabled(false);
        txtMaNV.setText(maNV);
        txtTenNV.setText(tenNV);
        try {
            txtNgaySinhNV.setDate(sdf.parse(ngaySinhNV));
        } catch (ParseException ex) {
            Logger.getLogger(QLNV.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (gioiTinhNV.equals("Nam")) {
            rdoNam.setSelected(true);
        } else {
            rdoNu.setSelected(true);
        }
        txtDiaChiNV.setText(diaChiNV);
        txtSoDT.setText(soDtNV);
        int imgW = lblImage.getWidth();
        int imgH = lblImage.getHeight();
        ImageIcon icon = new ImageIcon(new ImageIcon(image).getImage().getScaledInstance(imgW, imgH, Image.SCALE_DEFAULT));

        lblImage.setName(image);
        lblImage.setIcon(icon);
        lblImage.setHorizontalAlignment(JLabel.CENTER);
        lblImage.setVerticalAlignment(JLabel.CENTER);
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // TODO add your handling code here:
        String tenNV = txtTimKiem.getText();
        List<QLNhanVien> listNhanVien = _InhanVienService.findNhanVienByName(tenNV, tenNV);
        tblModel = (DefaultTableModel) tblNhanVien.getModel();
        tblModel.setRowCount(0);
        for (QLNhanVien nv : listNhanVien) {
            Object[] data = {
                nv.getMaNV(),
                nv.getTenNV(),
                nv.getGioiTinhNV() ? "Nam" : "Nữ",
                nv.getNgaySinhNV(),
                nv.getDiaChiNV(),
                nv.getSdtNV(),
                nv.getImage()};
            tblModel.addRow(data);

        }
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void btnOderByMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOderByMaNVActionPerformed
        // TODO add your handling code here:
        List<QLNhanVien> listNhanVien = _InhanVienService.OrderNhanVienByMaNV();
        tblModel = (DefaultTableModel) tblNhanVien.getModel();
        tblModel.setRowCount(0);
        for (QLNhanVien nv : listNhanVien) {
            Object[] data = {
                nv.getMaNV(),
                nv.getTenNV(),
                nv.getGioiTinhNV() ? "Nam" : "Nữ",
                nv.getNgaySinhNV(),
                nv.getDiaChiNV(),
                nv.getSdtNV(),
                nv.getImage()};
            tblModel.addRow(data);
        }
    }//GEN-LAST:event_btnOderByMaNVActionPerformed

    private void btnOderByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOderByNameActionPerformed
        // TODO add your handling code here:
        List<QLNhanVien> listNhanVien = _InhanVienService.OrderNhanVienByName();
        tblModel = (DefaultTableModel) tblNhanVien.getModel();
        tblModel.setRowCount(0);
        for (QLNhanVien nv : listNhanVien) {
            Object[] data = {
                nv.getMaNV(),
                nv.getTenNV(),
                nv.getGioiTinhNV() ? "Nam" : "Nữ",
                nv.getNgaySinhNV(),
                nv.getDiaChiNV(),
                nv.getSdtNV(),
                nv.getImage()};
            tblModel.addRow(data);
        }
    }//GEN-LAST:event_btnOderByNameActionPerformed

    private void btnOderByDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOderByDiaChiActionPerformed
        // TODO add your handling code here:
        List<QLNhanVien> listNhanVien = _InhanVienService.OrderNhanVienByDiaChi();
        tblModel = (DefaultTableModel) tblNhanVien.getModel();
        tblModel.setRowCount(0);
        for (QLNhanVien nv : listNhanVien) {
            Object[] data = {
                nv.getMaNV(),
                nv.getTenNV(),
                nv.getGioiTinhNV() ? "Nam" : "Nữ",
                nv.getNgaySinhNV(),
                nv.getDiaChiNV(),
                nv.getSdtNV(),
                nv.getImage()};
            tblModel.addRow(data);
        }
    }//GEN-LAST:event_btnOderByDiaChiActionPerformed

    private void btnClearChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearChucVuActionPerformed
        // TODO add your handling code here:
        this.clearFormChucVu();
    }//GEN-LAST:event_btnClearChucVuActionPerformed

    private void tblChucVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChucVuMouseClicked
        // TODO add your handling code here:
        int row = tblChucVu.getSelectedRow();

        String maChucVu = tblChucVu.getValueAt(row, 0).toString();
        String tenChucVu = tblChucVu.getValueAt(row, 1).toString();
        String moTa = tblChucVu.getValueAt(row, 2).toString();

        txtMaChucVu.setEnabled(false);
        txtMaChucVu.setText(maChucVu);
        txtTenChucVu.setText(tenChucVu);
        txtMoTa.setText(moTa);
    }//GEN-LAST:event_tblChucVuMouseClicked

    private void btnCleardTkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleardTkActionPerformed
        // TODO add your handling code here:
        this.clearFormTaiKhoan();
    }//GEN-LAST:event_btnCleardTkActionPerformed

    private void btnTimKiemTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemTKActionPerformed
        // TODO add your handling code here:
        String tenTK = txtTenTK.getText();
        if (tenTK.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mời nhập tên tài khoản",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (_ItaiKhoanService.getTaiKhoanByName(tenTK).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy tài khoản nào",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else {
            List<QLTaiKhoan> listTaiKhoan = _ItaiKhoanService.getTaiKhoanByName(tenTK);
            tblModel = (DefaultTableModel) tblTaiKhoan.getModel();
            tblModel.setRowCount(0);
            for (QLTaiKhoan tk : listTaiKhoan) {
                Object[] data = {
                    tk.getNhanVien().getMaNV(),
                    tk.getChucVu().getMaChucVu(),
                    tk.getTenTK(),
                    tk.getMatKhau(),
                    tk.getNgayLap()};
                tblModel.addRow(data);
            }
            JOptionPane.showMessageDialog(this, "Ðã tìm thấy nhân viên",
                    "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnTimKiemTKActionPerformed

    private void tblTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTaiKhoanMouseClicked
        // TODO add your handling code here:
        int row = tblTaiKhoan.getSelectedRow();

        String nhanVien = tblTaiKhoan.getValueAt(row, 0).toString();
        String chucVu = tblTaiKhoan.getValueAt(row, 1).toString();
        String tenTK = tblTaiKhoan.getValueAt(row, 2).toString();
        String matKhau = tblTaiKhoan.getValueAt(row, 3).toString();
        String ngayLap = tblTaiKhoan.getValueAt(row, 4).toString();

        cboNhanVien.setSelectedItem(nhanVien);
        cboChucVu.setSelectedItem(chucVu);
        txtTenTK.setText(tenTK);
        txtMatKhau.setText(matKhau);
        txtNgayLap.setText(ngayLap);
    }//GEN-LAST:event_tblTaiKhoanMouseClicked

    private void btnSaveNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveNhanVienActionPerformed
        // TODO add your handling code here:
        String maNV = txtMaNV.getText();
        String tenNV = txtTenNV.getText();
        Boolean gioiTinh;
        if (rdoNam.isSelected() == false && rdoNu.isSelected() == false) {
            gioiTinh = null;
        } else if (rdoNam.isSelected()) {
            gioiTinh = Boolean.TRUE;
        } else {
            gioiTinh = Boolean.FALSE;
        }
        Date ngaySinhNV = txtNgaySinhNV.getDate();
        String diaChiNV = txtDiaChiNV.getText();
        String soDtNV = txtSoDT.getText();
        String image = lblImage.getName();
        QLNhanVien qlnv = new QLNhanVien(maNV, tenNV, gioiTinh, ngaySinhNV, soDtNV, diaChiNV, image);
        if (qlnv.getMaNV().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mời nhập mã nhân viên",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (!qlnv.getMaNV().substring(0, 2).equalsIgnoreCase("NV")) {
            JOptionPane.showMessageDialog(this, "Mã nhân viên phải bắt đầu bằng NV",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (!_InhanVienService.getNhanVienByMaNV(maNV).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mã nhân viên đã tồn tại",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (qlnv.getTenNV().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mời nhập tên nhân viên ",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (qlnv.getGioiTinhNV() == null) {
            JOptionPane.showMessageDialog(this, "Mời chọn giới tính nhân viên",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (qlnv.getNgaySinhNV() == null) {
            JOptionPane.showMessageDialog(this, "Mời nhập ngày sinh nhân viên",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (qlnv.getDiaChiNV().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mời nhập địa chỉ nhân viên",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (qlnv.getSdtNV().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mời nhập số điện thoại nhân viên",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (!qlnv.getSdtNV().matches("0[0-9]{9}")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không đúng định dạng",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (qlnv.getImage() == null) {
            JOptionPane.showMessageDialog(this, "Mời chọn ảnh nhân viên",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (_InhanVienService.createNhanVien(qlnv) != null) {
            int chon = JOptionPane.showConfirmDialog(this, "Xác nhận thêm nhân viên");
            if (chon == JOptionPane.YES_OPTION) {
                filltoTableNhanVien();
                clearFormNhanVien();
                JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công",
                        "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Thêm nhân viên thất bại",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveNhanVienActionPerformed

    private void btnUpdateNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateNhanVienActionPerformed
        // TODO add your handling code here:
        select = tblNhanVien.getSelectedRow();
        String maNV = txtMaNV.getText();
        String tenNV = txtTenNV.getText();
        Boolean gioiTinh;
        if (rdoNam.isSelected()) {
            gioiTinh = Boolean.TRUE;
        } else {
            gioiTinh = Boolean.FALSE;
        }
        Date ngaySinhNV = txtNgaySinhNV.getDate();
        String diaChiNV = txtDiaChiNV.getText();
        String soDtNV = txtSoDT.getText();
        String image = lblImage.getName();
        QLNhanVien qlnv = new QLNhanVien(maNV, tenNV, gioiTinh, ngaySinhNV, soDtNV, diaChiNV, image);
        if (select == -1) {
            JOptionPane.showMessageDialog(this, "Chưa chọn nhân viên cần update",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (qlnv.getTenNV().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mời nhập tên nhân viên ",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (qlnv.getGioiTinhNV() == null) {
            JOptionPane.showMessageDialog(this, "Mời chọn giới tính nhân viên",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (qlnv.getNgaySinhNV() == null) {
            JOptionPane.showMessageDialog(this, "Mời nhập ngày sinh nhân viên",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (qlnv.getDiaChiNV().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mời nhập địa chỉ nhân viên",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (qlnv.getSdtNV().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mời nhập số điện thoại nhân viên",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (!qlnv.getSdtNV().matches("0[0-9]{9}")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không đúng định dạng",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (qlnv.getImage() == null) {
            JOptionPane.showMessageDialog(this, "Mời chọn ảnh nhân viên",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (_InhanVienService.updateNhanVien(qlnv) != null) {
            int chon = JOptionPane.showConfirmDialog(this, "Xác nhận sửa nhân viên");
            if (chon == JOptionPane.YES_OPTION) {
                filltoTableNhanVien();
                clearFormNhanVien();
                JOptionPane.showMessageDialog(this, "Sửa nhân viên thành công",
                        "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Sửa nhân viên thất bại",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateNhanVienActionPerformed

    private void btnDeleteNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteNhanVienActionPerformed
        // TODO add your handling code here:
        select = tblNhanVien.getSelectedRow();
        String maNV = tblNhanVien.getValueAt(select, 0).toString();
        if (select == -1) {
            JOptionPane.showMessageDialog(this, "Chưa chọn nhân viên cần xóa",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (_InhanVienService.deleteNhanVien(maNV) != null) {
            int chon = JOptionPane.showConfirmDialog(this, "Xác nhận sửa nhân viên");
            if (chon == JOptionPane.YES_OPTION) {
                filltoTableNhanVien();
                clearFormNhanVien();
                JOptionPane.showMessageDialog(this, "Xóa nhân viên thành công",
                        "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Xóa nhân viên thất bại",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteNhanVienActionPerformed

    private void btnClearNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearNhanVienActionPerformed
        // TODO add your handling code here:
        this.clearFormNhanVien();
    }//GEN-LAST:event_btnClearNhanVienActionPerformed

    private void btnFindNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindNhanVienActionPerformed
        // TODO add your handling code here:
        String maNV = txtMaNV.getText();
        if (maNV.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mời nhập mã nhân viên",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (_InhanVienService.getNhanVienByMaNV(maNV).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên nào",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else {
            List<QLNhanVien> listNhanVien = _InhanVienService.getNhanVienByMaNV(maNV);
            tblModel = (DefaultTableModel) tblNhanVien.getModel();
            tblModel.setRowCount(0);
            for (QLNhanVien nv : listNhanVien) {
                Object[] data = {
                    nv.getMaNV(),
                    nv.getTenNV(),
                    nv.getGioiTinhNV() ? "Nam" : "Nữ",
                    nv.getNgaySinhNV(),
                    nv.getDiaChiNV(),
                    nv.getSdtNV(),
                    nv.getImage()};
                tblModel.addRow(data);
            }
            JOptionPane.showMessageDialog(this, "Ðã tìm thấy nhân viên",
                    "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnFindNhanVienActionPerformed

    private void btnThemChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemChucVuActionPerformed
        // TODO add your handling code here:
        String maCV = txtMaChucVu.getText();
        String tenCV = txtTenChucVu.getText();
        String moTa = txtMoTa.getText();

        QLChucVu qlcv = new QLChucVu(maCV, tenCV, moTa);
        if (qlcv.getMaChucVu().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mời nhập mã chức vụ",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (!qlcv.getMaChucVu().substring(0, 2).equalsIgnoreCase("CV")) {
            JOptionPane.showMessageDialog(this, "Mã chức vụ phải bắt đầu bằng CV",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (!_IchucVuService.getChucVuByMa(maCV).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mã chức vụ đã tồn tại",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (qlcv.getTenChucVu().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mời nhập tên chức vụ",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (qlcv.getTenChucVu().matches("[a-zA-Z]")) {
            JOptionPane.showMessageDialog(this, "Tên chức vụ không đúng định dạng",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (_IchucVuService.createChucVu(qlcv) != null) {
            int chon = JOptionPane.showConfirmDialog(this, "Xác nhận thêm chức vụ");
            if (chon == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(this, "Thêm chức vụ thành công",
                        "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                filltoTableChucVu();
                clearFormChucVu();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Thêm chức vụ thất bại",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThemChucVuActionPerformed

    private void btnUpdateChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateChucVuActionPerformed
        // TODO add your handling code here:
        String maCV = txtMaChucVu.getText();
        String tenCV = txtTenChucVu.getText();
        String moTa = txtMoTa.getText();

        QLChucVu qlcv = new QLChucVu(maCV, tenCV, moTa);
        if (tblChucVu.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Chưa chọn chức vụ cần sửa",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (qlcv.getTenChucVu().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mời nhập tên chức vụ",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (qlcv.getTenChucVu().matches("[a-zA-Z]")) {
            JOptionPane.showMessageDialog(this, "Tên chức vụ không đúng định dạng",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (_IchucVuService.updateChucVu(qlcv) != null) {
            int chon = JOptionPane.showConfirmDialog(this, "Xác nhận sửa chức vụ");
            if (chon == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(this, "Sửa chức vụ thành công",
                        "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                filltoTableChucVu();
                clearFormChucVu();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Sửa chức vụ thất bại",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateChucVuActionPerformed

    private void btnDeleteChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteChucVuActionPerformed
        // TODO add your handling code here:        
        select = tblChucVu.getSelectedRow();
        String maCV = tblChucVu.getValueAt(select, 0).toString();
        if (select == -1) {
            JOptionPane.showMessageDialog(this, "Chưa chọn chức vụ cần xóa",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (_IchucVuService.deleteChucVu(maCV) != null) {
            int chon = JOptionPane.showConfirmDialog(this, "Xác nhận xóa chức vụ");
            if (chon == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(this, "Xóa chức vụ thành công",
                        "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                filltoTableChucVu();
                clearFormChucVu();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Xóa chức vụ thất bại",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteChucVuActionPerformed

    private void btnThemTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTKActionPerformed
        // TODO add your handling code here:
        QLNhanVien qlnv = _InhanVienService.getNhanVien((String) cboNhanVien.getSelectedItem());
        NhanVien nhanVien = new NhanVien(qlnv.getMaNV(), qlnv.getTenNV(), qlnv.getGioiTinhNV(), qlnv.getNgaySinhNV(), qlnv.getDiaChiNV(), qlnv.getSdtNV(), qlnv.getImage(), null, null);
        QLChucVu qlcv = _IchucVuService.getChucVu((String) cboChucVu.getSelectedItem());
        ChucVu chucVu = new ChucVu(qlcv.getMaChucVu(), qlcv.getTenChucVu(), qlcv.getMoTa());
        String tenTK = txtTenTK.getText();
        String matKhau = new String(txtMatKhau.getPassword());
        LocalDate localDate = LocalDate.now();
        String ngayLap = String.valueOf(localDate);

        QLTaiKhoan qltk = new QLTaiKhoan(tenTK, matKhau, nhanVien, chucVu, ngayLap);
        if (qltk.getTenTK().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mời nhập tên tài khoản",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (qltk.getMatKhau().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mời nhập mật khẩu",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (_ItaiKhoanService.createTaiKhoan(qltk) != null) {
            int chon = JOptionPane.showConfirmDialog(this, "Xác nhận thêm tài khoản");
            if (chon == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(this, "Thêm tài khoản thành công",
                        "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                filltoTableTaiKhoan();
                clearFormTaiKhoan();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Thêm tài khoản thất bại",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnThemTKActionPerformed

    private void btnSuaTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaTKActionPerformed
        // TODO add your handling code here:
        QLNhanVien qlnv = _InhanVienService.getNhanVien((String) cboNhanVien.getSelectedItem());
        NhanVien nhanVien = new NhanVien(qlnv.getMaNV(), qlnv.getTenNV(), qlnv.getGioiTinhNV(), qlnv.getNgaySinhNV(), qlnv.getDiaChiNV(), qlnv.getSdtNV(), qlnv.getImage(), null, null);
        QLChucVu qlcv = _IchucVuService.getChucVu((String) cboChucVu.getSelectedItem());
        ChucVu chucVu = new ChucVu(qlcv.getMaChucVu(), qlcv.getTenChucVu(), qlcv.getMoTa());
        String tenTK = txtTenTK.getText();
        String matKhau = new String(txtMatKhau.getPassword());
        LocalDate localDate = LocalDate.now();
        String ngayLap = String.valueOf(localDate);

        QLTaiKhoan qltk = new QLTaiKhoan(tenTK, matKhau, nhanVien, chucVu, ngayLap);
        if (qltk.getMatKhau().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mời nhập mật khẩu",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (_ItaiKhoanService.createTaiKhoan(qltk) != null) {
            int chon = JOptionPane.showConfirmDialog(this, "Xác nhận sửa tài khoản");
            if (chon == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(this, "Sửa tài khoản thành công",
                        "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                filltoTableTaiKhoan();
                clearFormTaiKhoan();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Sửa tài khoản thất bại",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSuaTKActionPerformed

    private void btnXoaTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTKActionPerformed
        // TODO add your handling code here:
        select = tblTaiKhoan.getSelectedRow();
        String tenTK = tblTaiKhoan.getValueAt(select, 2).toString();
        if (select == -1) {
            JOptionPane.showMessageDialog(this, "Chưa chọn tài khoản cần xóa",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (_ItaiKhoanService.deleteTaiKhoan(tenTK) != null) {
            int chon = JOptionPane.showConfirmDialog(this, "Xác nhận óa tài khoản");
            if (chon == JOptionPane.YES_OPTION) {
                filltoTableTaiKhoan();
                clearFormTaiKhoan();
                JOptionPane.showMessageDialog(this, "Xóa tài khoản thành công",
                        "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Xóa tài khoản thất bại",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnXoaTKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane J;
    private javax.swing.JScrollPane NHANVIEN;
    private javax.swing.JButton btnClearChucVu;
    private javax.swing.JButton btnClearNhanVien;
    private javax.swing.JButton btnCleardTk;
    private javax.swing.JButton btnDeleteChucVu;
    private javax.swing.JButton btnDeleteNhanVien;
    private javax.swing.JButton btnFindNhanVien;
    private javax.swing.JButton btnOderByDiaChi;
    private javax.swing.JButton btnOderByMaNV;
    private javax.swing.JButton btnOderByName;
    private javax.swing.JButton btnSaveNhanVien;
    private javax.swing.JButton btnSuaTK;
    private javax.swing.JButton btnThemChucVu;
    private javax.swing.JButton btnThemTK;
    private javax.swing.JButton btnTimKiemTK;
    private javax.swing.JButton btnUpdateChucVu;
    private javax.swing.JButton btnUpdateNhanVien;
    private javax.swing.JButton btnXoaTK;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboChucVu;
    private javax.swing.JComboBox<String> cboNhanVien;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblDiaChiNV;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblMaCVTK;
    private javax.swing.JLabel lblMaChucVu;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblMaNVTK;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblMoTa;
    private javax.swing.JLabel lblNgayLap;
    private javax.swing.JLabel lblNgaySinhNV;
    private javax.swing.JLabel lblSoDT;
    private javax.swing.JLabel lblTenChucVu;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JLabel lblTenTK;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable tblChucVu;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTable tblTaiKhoan;
    private javax.swing.JTextField txtDiaChiNV;
    private javax.swing.JTextField txtMaChucVu;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtNgayLap;
    private com.toedter.calendar.JDateChooser txtNgaySinhNV;
    private javax.swing.JTextField txtSoDT;
    private javax.swing.JTextField txtTenChucVu;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtTenTK;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
