/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import domainmodel.dKhachhang;
import domainmodel.dthuephong;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import services.IKhachhang;
import services.IPhong;
import services.Ithuephong;
import services.impl.KH_service;
import services.impl.Phong_service;
import services.impl.TPhong_service;

/**
 *
 * @author MrpDuy
 */
public class DatphongUI extends javax.swing.JFrame {

    IKhachhang khsv = new KH_service();
    IPhong sv_phong = new Phong_service();
    Ithuephong sv_thuep = new TPhong_service();
    List<dKhachhang> LKH;

    /**
     * Creates new form DatphongUI
     */
    public DatphongUI() {
        initComponents();
        setLocationRelativeTo(null);

    }
    public static String MaPhong;
    public static double GiaTheoGio, GiaTheoNgay;
    
    public dthuephong getdataphieu() {
        SimpleDateFormat s = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            dthuephong data = new dthuephong();
            data.setMaKH(cbocccd.getSelectedItem().toString());
            data.setMaPhong(lblphong.getText());
            if (rdogio.isSelected()) {
                data.setLoaiHinhThue(1);
            } else {
                data.setLoaiHinhThue(0);
            }
            data.setNgayThue(s.format(txtngaythue.getDate()));
            data.setNgayRaDuKien(s.format(txtngaytra.getDate()));
            data.setSoNguoi(Integer.parseInt(txtnguoi.getText()));
            data.setTenUser("duysp");
            data.setTrangthai(0);
            data.setTienCoc(Double.parseDouble(txttiencoc.getText()));
            return data;
    }

    /* public dthuephong getdataphieu(){
    SimpleDateFormat s = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
    String mkh = (String) cbocccd.getSelectedItem();
    String map = lblphong.getText();
    int loaithue;
        if (rdogio.isSelected()) {
            loaithue=0;
        }else{
        loaithue=1;
        }
    String nThue =  txtngaythue.getCalendar()+"";
    try {
            String nTra;
            nTra.setNgayRaDuKien(s.format(txtngaytra.getDate()));
        } catch (Exception e) {
            return;
        }
    int songuoi =Integer.parseInt(txtnguoi.getText());
    String user = "DuyAD";
    int tt =0;
    double Tien = Double.parseDouble(txttiencoc.getText());
    return new dthuephong(mkh, map,loaithue, nThue, nTra, songuoi, user, tt, Tien);
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rdongay = new javax.swing.JRadioButton();
        rdogio = new javax.swing.JRadioButton();
        cbocccd = new javax.swing.JComboBox<>();
        lblphong = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnguoi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtgiatien = new javax.swing.JTextField();
        btnthem = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btndat = new javax.swing.JButton();
        btnthue = new javax.swing.JButton();
        txtngaytra = new com.toedter.calendar.JDateChooser();
        txtngaythue = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        txttiencoc = new javax.swing.JTextField();
        backgr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Phiếu thuê phòng");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("UVN Thanh Pho", 1, 24)); // NOI18N
        jLabel1.setText("Phiếu thuê");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 100, 40));

        jLabel2.setText("Phòng:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        rdongay.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdongay);
        rdongay.setSelected(true);
        rdongay.setText("Theo ngày");
        rdongay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdongayActionPerformed(evt);
            }
        });
        getContentPane().add(rdongay, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        rdogio.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdogio);
        rdogio.setText("Theo giờ");
        rdogio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdogioActionPerformed(evt);
            }
        });
        getContentPane().add(rdogio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        cbocccd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbocccd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbocccdActionPerformed(evt);
            }
        });
        getContentPane().add(cbocccd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 150, 30));

        lblphong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblphong.setText("abc");
        getContentPane().add(lblphong, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 40, -1));

        jLabel4.setText("Ngày thuê:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jLabel5.setText("Khách hàng:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jLabel6.setText("Loại hình:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel7.setText("Người ở:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));
        getContentPane().add(txtnguoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 100, -1));

        jLabel8.setText("Giá tiền:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));
        getContentPane().add(txtgiatien, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 80, -1));

        btnthem.setBackground(new java.awt.Color(255, 255, 255));
        btnthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Plus_30px.png"))); // NOI18N
        btnthem.setBorder(null);
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });
        getContentPane().add(btnthem, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 40, -1));

        jLabel9.setText("Ngày trả(dự kiến):");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btndat.setText("Đặt trước");
        btndat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndatActionPerformed(evt);
            }
        });
        jPanel1.add(btndat);

        btnthue.setText("Thuê phòng");
        btnthue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthueActionPerformed(evt);
            }
        });
        jPanel1.add(btnthue);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, -1, 40));

        txtngaytra.setDateFormatString("yyyy-MM-dd");
        txtngaytra.setPreferredSize(new java.awt.Dimension(70, 22));
        getContentPane().add(txtngaytra, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 140, 25));

        txtngaythue.setDateFormatString("yyyy-MM-dd ");
        txtngaythue.setPreferredSize(new java.awt.Dimension(70, 22));
        getContentPane().add(txtngaythue, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 272, 140, 25));

        jLabel10.setText("Tiền cọc:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));
        getContentPane().add(txttiencoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 100, -1));

        backgr.setBackground(new java.awt.Color(255, 255, 255));
        backgr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backgr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backgr.png"))); // NOI18N
        getContentPane().add(backgr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndatActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cbocccd.removeAllItems();
        LKH = khsv.getAlldataKH();
        for (int i = 0; i < LKH.size(); i++) {
            cbocccd.addItem(LKH.get(i).getMaKH());
        }
        lblphong.setForeground(Color.decode("#000000"));
        lblphong.setText(String.valueOf(MaPhong));
        if (rdogio.isSelected()) {
            txtgiatien.setText(GiaTheoGio + "");
        } else {
            txtgiatien.setText(GiaTheoNgay + "");
        }
    }//GEN-LAST:event_formWindowOpened

    private void rdongayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdongayActionPerformed

        txtgiatien.setText(GiaTheoNgay + "");

    }//GEN-LAST:event_rdongayActionPerformed

    private void rdogioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdogioActionPerformed

        txtgiatien.setText(GiaTheoGio + "");

    }//GEN-LAST:event_rdogioActionPerformed

    private void cbocccdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbocccdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbocccdActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
            MenuUIFull frm = MenuUIFull.b;
            
            pnl_Khachhang pnl = new pnl_Khachhang();
            frm.tab.add("Danh sách phòng", pnl);
            frm.tab.setSelectedComponent(pnl);
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnthueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthueActionPerformed
        try {
            dthuephong data= getdataphieu();
           int chon= JOptionPane.showConfirmDialog(null, "Xác nhận đặt phòng","Đặt phòng",JOptionPane.OK_CANCEL_OPTION);
           if(chon==0){
            sv_thuep.themthuep(data);
            JOptionPane.showMessageDialog(this, "Thuê phòng thành công");
            sv_phong.doitt(2,MaPhong);
            //mở lại form thuê phòng
            MenuUIFull frm = MenuUIFull.b;
            frm.tab.remove(pnl_datphong.form);
            pnl_datphong pnl = new pnl_datphong();
            frm.tab.add("Danh sách phòng", pnl);
            frm.tab.setSelectedComponent(pnl);
            this.dispose();
           }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnthueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */


 /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatphongUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgr;
    private javax.swing.JButton btndat;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnthue;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbocccd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblphong;
    private javax.swing.JRadioButton rdogio;
    private javax.swing.JRadioButton rdongay;
    private javax.swing.JTextField txtgiatien;
    private com.toedter.calendar.JDateChooser txtngaythue;
    private com.toedter.calendar.JDateChooser txtngaytra;
    private javax.swing.JTextField txtnguoi;
    private javax.swing.JTextField txttiencoc;
    // End of variables declaration//GEN-END:variables
}
