/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author MrpDuy
 */
public class MenuUIFull extends javax.swing.JFrame {

    javax.swing.border.Border a = BorderFactory.createLineBorder(Color.black, 2, true);
    javax.swing.border.Border empty = BorderFactory.createEmptyBorder();
    public static MenuUIFull b;

    /**
     * Creates new form MenuUI
     */
    public MenuUIFull() {
        initComponents();
        setLocationRelativeTo(null);
        b=this;
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        btndichvu = new javax.swing.JButton();
        btnkhachhang = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        btnroom = new javax.swing.JButton();
        btndatphong = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        tab = new javax.swing.JTabbedPane();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mntaikhoan = new javax.swing.JMenu();
        mndoimk = new javax.swing.JMenuItem();
        mkthoat = new javax.swing.JMenuItem();
        mnnhanvien = new javax.swing.JMenu();
        mndsnv = new javax.swing.JMenuItem();
        mndstk = new javax.swing.JMenuItem();
        mnthongke = new javax.swing.JMenu();
        mndoanhthu = new javax.swing.JMenuItem();
        mntknhanvien = new javax.swing.JMenuItem();
        mnphong = new javax.swing.JMenuItem();
        mnhoadon = new javax.swing.JMenu();
        mnthongtin = new javax.swing.JMenu();
        mncauhinh = new javax.swing.JMenu();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ KHÁCH SẠN THE POLY");
        setBackground(new java.awt.Color(204, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(1920, 1080));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(268, 1016));
        jPanel1.setPreferredSize(new java.awt.Dimension(268, 1016));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setVerifyInputWhenFocusTarget(false);

        btndichvu.setBackground(new java.awt.Color(255, 255, 255));
        btndichvu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btndichvu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_technical_support_wearing_glasses_30px.png"))); // NOI18N
        btndichvu.setText("DỊCH VỤ");
        btndichvu.setBorder(null);
        btndichvu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndichvu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btndichvuMouseMoved(evt);
            }
        });
        btndichvu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndichvuMouseClicked(evt);
            }
        });
        btndichvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndichvuActionPerformed(evt);
            }
        });

        btnkhachhang.setBackground(new java.awt.Color(255, 255, 255));
        btnkhachhang.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnkhachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_customer_30px.png"))); // NOI18N
        btnkhachhang.setText("KHÁCH HÀNG");
        btnkhachhang.setBorder(null);
        btnkhachhang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnkhachhang.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnkhachhangMouseMoved(evt);
            }
        });
        btnkhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnkhachhangMouseClicked(evt);
            }
        });
        btnkhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhachhangActionPerformed(evt);
            }
        });

        btnhome.setBackground(new java.awt.Color(255, 255, 255));
        btnhome.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_home_page_30px.png"))); // NOI18N
        btnhome.setText("TRANG CHỦ");
        btnhome.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnhome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnhome.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnhomeMouseMoved(evt);
            }
        });
        btnhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhomeMouseClicked(evt);
            }
        });
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });

        btnlogout.setBackground(new java.awt.Color(255, 255, 255));
        btnlogout.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_go_back_30px_1.png"))); // NOI18N
        btnlogout.setText("ĐĂNG XUẤT");
        btnlogout.setBorder(null);
        btnlogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlogout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnlogoutMouseMoved(evt);
            }
        });
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        btnroom.setBackground(new java.awt.Color(255, 255, 255));
        btnroom.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnroom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_hotel_bed_30px.png"))); // NOI18N
        btnroom.setText("PHÒNG");
        btnroom.setBorder(null);
        btnroom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnroom.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnroomMouseMoved(evt);
            }
        });
        btnroom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnroomMouseClicked(evt);
            }
        });
        btnroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnroomActionPerformed(evt);
            }
        });

        btndatphong.setBackground(new java.awt.Color(255, 255, 255));
        btndatphong.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btndatphong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_hotel_building_30px.png"))); // NOI18N
        btndatphong.setText("ĐẶT PHÒNG");
        btndatphong.setBorder(null);
        btndatphong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndatphong.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btndatphongMouseMoved(evt);
            }
        });
        btndatphong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndatphongMouseClicked(evt);
            }
        });
        btndatphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndatphongActionPerformed(evt);
            }
        });

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo100.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnlogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btndatphong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btndichvu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnroom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnkhachhang, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
            .addComponent(btnhome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnhome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndatphong, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndichvu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnroom, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Menu.setBackground(new java.awt.Color(204, 204, 204));
        Menu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Menu.setRequestFocusEnabled(false);
        Menu.setVerifyInputWhenFocusTarget(false);

        tab.setBackground(new java.awt.Color(0, 153, 255));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_close_30px_1.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(tab, javax.swing.GroupLayout.DEFAULT_SIZE, 1555, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(3, 3, 3))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 928, Short.MAX_VALUE))
                    .addComponent(tab))
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));
        jMenuBar1.setToolTipText("");
        jMenuBar1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jMenuBar1.setMinimumSize(new java.awt.Dimension(646, 60));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(646, 60));

        mntaikhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_name_50px.png"))); // NOI18N
        mntaikhoan.setText("Tài khoản");
        mntaikhoan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mntaikhoan.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mntaikhoanMouseMoved(evt);
            }
        });

        mndoimk.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mndoimk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_replace_30px.png"))); // NOI18N
        mndoimk.setText("Đổi mật khẩu");
        mndoimk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mndoimkActionPerformed(evt);
            }
        });
        mntaikhoan.add(mndoimk);

        mkthoat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mkthoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_enter_30px.png"))); // NOI18N
        mkthoat.setText("Thoát");
        mkthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mkthoatActionPerformed(evt);
            }
        });
        mntaikhoan.add(mkthoat);

        jMenuBar1.add(mntaikhoan);

        mnnhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_member_30px.png"))); // NOI18N
        mnnhanvien.setText("Nhân viên");
        mnnhanvien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mndsnv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mndsnv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_list_30px.png"))); // NOI18N
        mndsnv.setText("Danh sách nhân viên");
        mnnhanvien.add(mndsnv);

        mndstk.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mndstk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_list_30px.png"))); // NOI18N
        mndstk.setText("Danh sách tài khoản");
        mndstk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mndstkActionPerformed(evt);
            }
        });
        mnnhanvien.add(mndstk);

        jMenuBar1.add(mnnhanvien);

        mnthongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_cloud_bar_chart_30px.png"))); // NOI18N
        mnthongke.setText("Thống kê");
        mnthongke.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mndoanhthu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mndoanhthu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_paid_bill_30px_2.png"))); // NOI18N
        mndoanhthu.setText("Doanh thu");
        mnthongke.add(mndoanhthu);

        mntknhanvien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mntknhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_member_30px.png"))); // NOI18N
        mntknhanvien.setText("Nhân viên");
        mntknhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntknhanvienActionPerformed(evt);
            }
        });
        mnthongke.add(mntknhanvien);

        mnphong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnphong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_hotel_bed_30px.png"))); // NOI18N
        mnphong.setText("Phòng");
        mnphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnphongActionPerformed(evt);
            }
        });
        mnthongke.add(mnphong);

        jMenuBar1.add(mnthongke);

        mnhoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_paid_bill_30px_2.png"))); // NOI18N
        mnhoadon.setText("Hóa đơn");
        mnhoadon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(mnhoadon);

        mnthongtin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_information_30px.png"))); // NOI18N
        mnthongtin.setText("Thông tin ");
        mnthongtin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(mnthongtin);

        mncauhinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_settings_30px.png"))); // NOI18N
        mncauhinh.setText("Cấu hình");
        mncauhinh.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuBar1.add(mncauhinh);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 973, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(Menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndichvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndichvuActionPerformed
       try {
            tab.setSelectedComponent(FormDV.form);
        } catch (Exception e) {
            //tab.remove(pnl_DSphong.form);
            FormDV pnl = new FormDV();
            tab.add("Dịch vụ", pnl);
            tab.setSelectedComponent(pnl);
        }
    }//GEN-LAST:event_btndichvuActionPerformed

    private void btndatphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndatphongActionPerformed
       try {
            tab.setSelectedComponent(pnl_DSThuephong.form);
        } catch (Exception e) {
            //tab.remove(pnl_DSphong.form);
            pnl_DSThuephong pnl = new pnl_DSThuephong();
            tab.add("Danh sách thuê phòng", pnl);
            tab.setSelectedComponent(pnl);
        }
    }//GEN-LAST:event_btndatphongActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        btndatphong.setBackground(Color.white);
        btndatphong.setBorder(empty);
        btndichvu.setBackground(Color.white);
        btndichvu.setBorder(empty);
        btnhome.setBackground(Color.white);
        btnhome.setBorder(empty);
        btnlogout.setBackground(Color.white);
        btnlogout.setBorder(empty);
        btnroom.setBackground(Color.white);
        btnroom.setBorder(empty);
        btnkhachhang.setBackground(Color.white);
        btnkhachhang.setBorder(empty);
        btnlogout.setForeground(Color.black);
    }//GEN-LAST:event_formMouseMoved

    private void btnroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnroomActionPerformed
        try {
            tab.setSelectedComponent(pnl_Phong.form);
        } catch (Exception e) {
//            tab.remove(pnl_Phong.form);
            pnl_Phong pnl = new pnl_Phong();
            tab.add("Quản lý phòng", pnl);
            tab.setSelectedComponent(pnl);

        }
    }//GEN-LAST:event_btnroomActionPerformed

    private void btnhomeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomeMouseMoved
        btnhome.setBackground(Color.decode("#FFFF99"));
        btnhome.setBorder(a);
    }//GEN-LAST:event_btnhomeMouseMoved

    private void btndatphongMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatphongMouseMoved
        btndatphong.setBackground(Color.decode("#FFFF99"));
        btndatphong.setBorder(a);
    }//GEN-LAST:event_btndatphongMouseMoved

    private void btndichvuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndichvuMouseMoved
        btndichvu.setBackground(Color.decode("#FFFF99"));
        btndichvu.setBorder(a);
    }//GEN-LAST:event_btndichvuMouseMoved

    private void btnroomMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnroomMouseMoved
        btnroom.setBackground(Color.decode("#FFFF99"));
        btnroom.setBorder(a);
    }//GEN-LAST:event_btnroomMouseMoved

    private void btnkhachhangMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkhachhangMouseMoved
        btnkhachhang.setBorder(a);
        btnkhachhang.setBackground(Color.decode("#FFFF99"));
    }//GEN-LAST:event_btnkhachhangMouseMoved

    private void btnlogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseMoved
        btnlogout.setBackground(Color.decode("#E90929"));
        btnlogout.setForeground(Color.white);
        btnlogout.setBorder(a);
    }//GEN-LAST:event_btnlogoutMouseMoved

    private void btnhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomeMouseClicked

    }//GEN-LAST:event_btnhomeMouseClicked

    private void btndatphongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatphongMouseClicked

    }//GEN-LAST:event_btndatphongMouseClicked

    private void btndichvuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndichvuMouseClicked

    }//GEN-LAST:event_btndichvuMouseClicked

    private void btnroomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnroomMouseClicked

    }//GEN-LAST:event_btnroomMouseClicked

    private void btnkhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkhachhangMouseClicked

    }//GEN-LAST:event_btnkhachhangMouseClicked

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed

    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
         try {
            tab.setSelectedComponent(pnl_datphong.form);
        } catch (Exception e) {
//            tab.remove(pnl_Phong.form);
            pnl_datphong pnl = new pnl_datphong();
            tab.add("Đặt phòng", pnl);
            tab.setSelectedComponent(pnl);

        }
    }//GEN-LAST:event_btnhomeActionPerformed

    private void mkthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mkthoatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mkthoatActionPerformed

    private void mndstkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mndstkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mndstkActionPerformed

    private void mntknhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntknhanvienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mntknhanvienActionPerformed

    private void mnphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnphongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnphongActionPerformed

    private void mndoimkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mndoimkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mndoimkActionPerformed

    private void btnkhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhachhangActionPerformed
        try {
            tab.setSelectedComponent(pnl_Khachhang.form);
        } catch (Exception e) {
            //tab.remove(pnl_DSphong.form);
            pnl_Khachhang pnl = new pnl_Khachhang();
            tab.add("Quản lý khách hàng", pnl);
            tab.setSelectedComponent(pnl);

        }
    }//GEN-LAST:event_btnkhachhangActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tab.getTabCount() != 0) {
            tab.remove(tab.getSelectedComponent());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mntaikhoanMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mntaikhoanMouseMoved
        mntaikhoan.setBackground(Color.decode("#FFFF99"));
        mntaikhoan.setBorder(a);
    }//GEN-LAST:event_mntaikhoanMouseMoved

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            tab.setSelectedComponent(pnl_datphong.form);
        } catch (Exception e) {
//            tab.remove(pnl_Phong.form);
            pnl_datphong pnl = new pnl_datphong();
            tab.add("Đặt phòng", pnl);
            tab.setSelectedComponent(pnl);

        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUIFull().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JButton btndatphong;
    private javax.swing.JButton btndichvu;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnkhachhang;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnroom;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JLabel logo;
    private javax.swing.JMenuItem mkthoat;
    private javax.swing.JMenu mncauhinh;
    private javax.swing.JMenuItem mndoanhthu;
    private javax.swing.JMenuItem mndoimk;
    private javax.swing.JMenuItem mndsnv;
    private javax.swing.JMenuItem mndstk;
    private javax.swing.JMenu mnhoadon;
    private javax.swing.JMenu mnnhanvien;
    private javax.swing.JMenuItem mnphong;
    private javax.swing.JMenu mntaikhoan;
    private javax.swing.JMenu mnthongke;
    private javax.swing.JMenu mnthongtin;
    private javax.swing.JMenuItem mntknhanvien;
    public javax.swing.JTabbedPane tab;
    // End of variables declaration//GEN-END:variables
}
