/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import domainmodel.dKhachhang;
import java.util.List;
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.NotFoundException;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import domainmodel.dphong;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.IPhong;
import services.impl.Phong_service;
import viewmodel.vPhong;


/**
 *
 * @author MrpDuy
 */
public class pnl_Phong extends javax.swing.JPanel  {
    public static pnl_Phong form;
    IPhong khsv = new Phong_service();
    List<vPhong> LVP;
    List<dphong> LDP;
    DefaultTableModel mol;
    int index;
    
    /**
     * Creates new form KhachhangUI
     */
    public pnl_Phong() {
        initComponents();
        form = this;
        cbox();
        filltable();
        
    }
    
    public void filltable() {
        LVP = khsv.getAlldataPhong();
        mol = (DefaultTableModel) tblphong.getModel();
        mol.setRowCount(0);
        for (int i = 0; i < LVP.size(); i++) {
            Object[] data = new Object[]{LVP.get(i).getMap(), 
                LVP.get(i).getMaloaip(), LVP.get(i).getDientich(),LVP.get(i).getMat(),
                LVP.get(i).getHinh(),LVP.get(i).tinhtrag(),LVP.get(i).getGchu()};
            mol.addRow(data);
        }
    }
    public void showdetail() {
        vPhong p = LVP.get(index);
        txtmap.setText(p.getMap());
        cboloaip.setSelectedItem(p.getLoaip());
        txtdientich.setText(p.getDientich()+"");
        txttang.setText(p.getMat()+"");
        txtghichu.setText(p.getGchu());
        hinhanh.setText("");
        cbotinhtrang.setSelectedItem(p.tinhtrag());
        tblphong.setRowSelectionInterval(index, index);
    }

    public void cbox(){
    cbotinhtrang.removeAllItems();
    LVP = khsv.getAlldataPhong();
        for (int i = 0; i < LVP.size(); i++) {
            cbotinhtrang.addItem(LVP.get(i).tinhtrag());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jSpinner1 = new javax.swing.JSpinner();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnl_Phong = new javax.swing.JPanel();
        pane_nut = new javax.swing.JPanel();
        txtdientich = new javax.swing.JTextField();
        txtmap = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboloaip = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txttang = new javax.swing.JTextField();
        cbotang = new javax.swing.JComboBox<>();
        rdotang = new javax.swing.JRadioButton();
        rdotang2 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        hinhanh = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        p_nut = new javax.swing.JPanel();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnnew = new javax.swing.JButton();
        cbotinhtrang = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtghichu = new javax.swing.JTextArea();
        pane_bang = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblphong = new javax.swing.JTable();
        pnl_Loaiphong = new javax.swing.JPanel();
        pane_nut1 = new javax.swing.JPanel();
        txtdientich1 = new javax.swing.JTextField();
        txtmap1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cboloaip1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txttang1 = new javax.swing.JTextField();
        cbotang1 = new javax.swing.JComboBox<>();
        rdotang1 = new javax.swing.JRadioButton();
        rdotang3 = new javax.swing.JRadioButton();
        txtgiuongdon1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        hinhanh1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        p_nut1 = new javax.swing.JPanel();
        btnthem1 = new javax.swing.JButton();
        btnsua1 = new javax.swing.JButton();
        btnxoa1 = new javax.swing.JButton();
        btnnew1 = new javax.swing.JButton();
        txtgdoi1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cbotinhtrang1 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtghichu1 = new javax.swing.JTextArea();
        pane_bang1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblphong1 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1565, 600));
        setRequestFocusEnabled(false);

        pane_nut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Diện tích:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Phòng:");

        cboloaip.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboloaip.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PVIP01" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Loại :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Tầng :");

        cbotang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbotang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonGroup1.add(rdotang);
        rdotang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        buttonGroup1.add(rdotang2);
        rdotang2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(hinhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hinhanh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel1.setText("Hình ảnh");

        p_nut.setLayout(new java.awt.GridLayout(1, 0));

        btnthem.setBackground(new java.awt.Color(255, 255, 255));
        btnthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_add_30px_1.png"))); // NOI18N
        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setBackground(new java.awt.Color(255, 255, 255));
        btnsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_refresh_30px.png"))); // NOI18N
        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setBackground(new java.awt.Color(255, 255, 255));
        btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_delete_30px.png"))); // NOI18N
        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnnew.setBackground(new java.awt.Color(255, 255, 255));
        btnnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_new_30px.png"))); // NOI18N
        btnnew.setText("Làm mới");

        cbotinhtrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "trống", "sudung", "dọn", "dattruoc" }));
        cbotinhtrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbotinhtrangActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Tình trạng:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Ghi chú:");

        txtghichu.setColumns(20);
        txtghichu.setRows(5);
        jScrollPane2.setViewportView(txtghichu);

        javax.swing.GroupLayout pane_nutLayout = new javax.swing.GroupLayout(pane_nut);
        pane_nut.setLayout(pane_nutLayout);
        pane_nutLayout.setHorizontalGroup(
            pane_nutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_nutLayout.createSequentialGroup()
                .addGroup(pane_nutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pane_nutLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pane_nutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(40, 40, 40)
                        .addGroup(pane_nutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboloaip, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtmap, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(txtdientich, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addGroup(pane_nutLayout.createSequentialGroup()
                                .addGroup(pane_nutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txttang, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbotang, javax.swing.GroupLayout.Alignment.LEADING, 0, 126, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(pane_nutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdotang)
                                    .addComponent(rdotang2))))
                        .addGroup(pane_nutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pane_nutLayout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabel12)
                                .addGap(26, 26, 26)
                                .addComponent(cbotinhtrang, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pane_nutLayout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(jLabel13)
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pane_nutLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnnew)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 449, Short.MAX_VALUE)
                .addGroup(pane_nutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_nutLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_nutLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(159, 159, 159))))
            .addGroup(pane_nutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pane_nutLayout.createSequentialGroup()
                    .addGap(542, 542, 542)
                    .addComponent(p_nut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(990, Short.MAX_VALUE)))
        );

        pane_nutLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cboloaip, txtdientich, txtmap});

        pane_nutLayout.setVerticalGroup(
            pane_nutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_nutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pane_nutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pane_nutLayout.createSequentialGroup()
                        .addGroup(pane_nutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pane_nutLayout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(23, 23, 23))
                            .addGroup(pane_nutLayout.createSequentialGroup()
                                .addGroup(pane_nutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbotinhtrang, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(pane_nutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(pane_nutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btnthem)
                            .addComponent(btnsua)
                            .addComponent(btnxoa)
                            .addComponent(btnnew))
                        .addGap(22, 22, 22))
                    .addGroup(pane_nutLayout.createSequentialGroup()
                        .addGroup(pane_nutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(pane_nutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboloaip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(23, 23, 23)
                        .addGroup(pane_nutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdientich, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pane_nutLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pane_nutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdotang, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pane_nutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(cbotang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pane_nutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txttang, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdotang2))
                        .addGap(85, 85, 85))))
            .addGroup(pane_nutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pane_nutLayout.createSequentialGroup()
                    .addGap(116, 116, 116)
                    .addComponent(p_nut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(175, Short.MAX_VALUE)))
        );

        pane_nutLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cboloaip, txtdientich, txtmap});

        pane_bang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tblphong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Phòng", "Loại phòng", "Diện tích", "Tầng", "Hình", "Tình trạng", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblphong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblphongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblphong);

        javax.swing.GroupLayout pane_bangLayout = new javax.swing.GroupLayout(pane_bang);
        pane_bang.setLayout(pane_bangLayout);
        pane_bangLayout.setHorizontalGroup(
            pane_bangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_bangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1510, Short.MAX_VALUE)
                .addContainerGap())
        );
        pane_bangLayout.setVerticalGroup(
            pane_bangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_bangLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout pnl_PhongLayout = new javax.swing.GroupLayout(pnl_Phong);
        pnl_Phong.setLayout(pnl_PhongLayout);
        pnl_PhongLayout.setHorizontalGroup(
            pnl_PhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane_nut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pane_bang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_PhongLayout.setVerticalGroup(
            pnl_PhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_PhongLayout.createSequentialGroup()
                .addComponent(pane_nut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pane_bang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Phòng", pnl_Phong);

        pane_nut1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Diện tích:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Phòng:");

        cboloaip1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboloaip1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PVIP01" }));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Loại :");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Tầng :");

        cbotang1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbotang1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonGroup1.add(rdotang1);
        rdotang1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        buttonGroup1.add(rdotang3);
        rdotang3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Giường đơn:");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(hinhanh1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hinhanh1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel2.setText("Hình ảnh");

        p_nut1.setLayout(new java.awt.GridLayout(1, 0));

        btnthem1.setBackground(new java.awt.Color(255, 255, 255));
        btnthem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_add_30px_1.png"))); // NOI18N
        btnthem1.setText("Thêm");
        btnthem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthem1ActionPerformed(evt);
            }
        });

        btnsua1.setBackground(new java.awt.Color(255, 255, 255));
        btnsua1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_refresh_30px.png"))); // NOI18N
        btnsua1.setText("Sửa");
        btnsua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsua1ActionPerformed(evt);
            }
        });

        btnxoa1.setBackground(new java.awt.Color(255, 255, 255));
        btnxoa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_delete_30px.png"))); // NOI18N
        btnxoa1.setText("Xóa");
        btnxoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoa1ActionPerformed(evt);
            }
        });

        btnnew1.setBackground(new java.awt.Color(255, 255, 255));
        btnnew1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_new_30px.png"))); // NOI18N
        btnnew1.setText("Làm mới");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Giường đôi:");

        cbotinhtrang1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trống", "sudung", "dọn", "dattruoc" }));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Tình trạng:");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Ghi chú:");

        txtghichu1.setColumns(20);
        txtghichu1.setRows(5);
        jScrollPane3.setViewportView(txtghichu1);

        javax.swing.GroupLayout pane_nut1Layout = new javax.swing.GroupLayout(pane_nut1);
        pane_nut1.setLayout(pane_nut1Layout);
        pane_nut1Layout.setHorizontalGroup(
            pane_nut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_nut1Layout.createSequentialGroup()
                .addGroup(pane_nut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pane_nut1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pane_nut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(40, 40, 40)
                        .addGroup(pane_nut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pane_nut1Layout.createSequentialGroup()
                                .addGroup(pane_nut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboloaip1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtmap1)
                                    .addComponent(txtdientich1))
                                .addGap(120, 120, 120)
                                .addGroup(pane_nut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pane_nut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel18)
                                        .addComponent(jLabel17))
                                    .addGroup(pane_nut1Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addGroup(pane_nut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel19)))))
                            .addGroup(pane_nut1Layout.createSequentialGroup()
                                .addGroup(pane_nut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txttang1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbotang1, javax.swing.GroupLayout.Alignment.LEADING, 0, 126, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(pane_nut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdotang1)
                                    .addComponent(rdotang3)))))
                    .addGroup(pane_nut1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnthem1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnsua1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnxoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnnew1)))
                .addGap(18, 18, 18)
                .addGroup(pane_nut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pane_nut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtgdoi1)
                        .addComponent(txtgiuongdon1)
                        .addComponent(cbotinhtrang1, 0, 110, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 432, Short.MAX_VALUE)
                .addGroup(pane_nut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_nut1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_nut1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(159, 159, 159))))
            .addGroup(pane_nut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pane_nut1Layout.createSequentialGroup()
                    .addGap(542, 542, 542)
                    .addComponent(p_nut1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(990, Short.MAX_VALUE)))
        );
        pane_nut1Layout.setVerticalGroup(
            pane_nut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_nut1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pane_nut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pane_nut1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(23, 23, 23)
                        .addGroup(pane_nut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(btnthem1)
                            .addComponent(btnsua1)
                            .addComponent(btnxoa1)
                            .addComponent(btnnew1))
                        .addGap(22, 22, 22))
                    .addGroup(pane_nut1Layout.createSequentialGroup()
                        .addGroup(pane_nut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pane_nut1Layout.createSequentialGroup()
                                .addGroup(pane_nut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmap1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(pane_nut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cboloaip1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)))
                            .addGroup(pane_nut1Layout.createSequentialGroup()
                                .addGroup(pane_nut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(txtgiuongdon1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(pane_nut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(txtgdoi1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(pane_nut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pane_nut1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(pane_nut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtdientich1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pane_nut1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pane_nut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdotang1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pane_nut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16)
                                        .addComponent(cbotang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(pane_nut1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(pane_nut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbotinhtrang1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(pane_nut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pane_nut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txttang1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rdotang3))
                            .addComponent(jLabel20)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))))
            .addGroup(pane_nut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pane_nut1Layout.createSequentialGroup()
                    .addGap(116, 116, 116)
                    .addComponent(p_nut1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(175, Short.MAX_VALUE)))
        );

        pane_bang1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tblphong1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Phòng", "Loại phòng", "Diện tích", "Tầng", "Giường đơn", "Giường đôi", "Hình", "Tình trạng", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblphong1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblphong1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblphong1);

        javax.swing.GroupLayout pane_bang1Layout = new javax.swing.GroupLayout(pane_bang1);
        pane_bang1.setLayout(pane_bang1Layout);
        pane_bang1Layout.setHorizontalGroup(
            pane_bang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_bang1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1486, Short.MAX_VALUE)
                .addContainerGap())
        );
        pane_bang1Layout.setVerticalGroup(
            pane_bang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_bang1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout pnl_LoaiphongLayout = new javax.swing.GroupLayout(pnl_Loaiphong);
        pnl_Loaiphong.setLayout(pnl_LoaiphongLayout);
        pnl_LoaiphongLayout.setHorizontalGroup(
            pnl_LoaiphongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_LoaiphongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_LoaiphongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pane_nut1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pane_bang1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_LoaiphongLayout.setVerticalGroup(
            pnl_LoaiphongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_LoaiphongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pane_nut1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pane_bang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Loại Phòng", pnl_Loaiphong);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
         try {
            dphong p = getbyform();
            
                 khsv.themPhong(p);
                    JOptionPane.showMessageDialog(this, "Thêm rất thành công");
                    filltable();
   
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        dphong p = getbyform();
        int chon = JOptionPane.showConfirmDialog(null, "Xóa phòng?","Xóa",JOptionPane.OK_CANCEL_OPTION);
        khsv.xoaPhong(p);
        JOptionPane.showMessageDialog(this, "xoa thanh cong");
        filltable();
    }//GEN-LAST:event_btnxoaActionPerformed

    private void tblphongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblphongMouseClicked
        index= tblphong.getSelectedRow();
        showdetail();
    }//GEN-LAST:event_tblphongMouseClicked

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        dphong p = getbyform();
        khsv.suaPhong(p);
        filltable();
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnthem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnthem1ActionPerformed

    private void btnsua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsua1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsua1ActionPerformed

    private void btnxoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnxoa1ActionPerformed

    private void tblphong1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblphong1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblphong1MouseClicked

    private void cbotinhtrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbotinhtrangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbotinhtrangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnnew1;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnsua1;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnthem1;
    private javax.swing.JButton btnxoa;
    private javax.swing.JButton btnxoa1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cboloaip;
    private javax.swing.JComboBox<String> cboloaip1;
    private javax.swing.JComboBox<String> cbotang;
    private javax.swing.JComboBox<String> cbotang1;
    private javax.swing.JComboBox<String> cbotinhtrang;
    private javax.swing.JComboBox<String> cbotinhtrang1;
    private javax.swing.JLabel hinhanh;
    private javax.swing.JLabel hinhanh1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel p_nut;
    private javax.swing.JPanel p_nut1;
    private javax.swing.JPanel pane_bang;
    private javax.swing.JPanel pane_bang1;
    private javax.swing.JPanel pane_nut;
    private javax.swing.JPanel pane_nut1;
    private javax.swing.JPanel pnl_Loaiphong;
    private javax.swing.JPanel pnl_Phong;
    private javax.swing.JRadioButton rdotang;
    private javax.swing.JRadioButton rdotang1;
    private javax.swing.JRadioButton rdotang2;
    private javax.swing.JRadioButton rdotang3;
    private javax.swing.JTable tblphong;
    private javax.swing.JTable tblphong1;
    private javax.swing.JTextField txtdientich;
    private javax.swing.JTextField txtdientich1;
    private javax.swing.JTextField txtgdoi1;
    private javax.swing.JTextArea txtghichu;
    private javax.swing.JTextArea txtghichu1;
    private javax.swing.JTextField txtgiuongdon1;
    private javax.swing.JTextField txtmap;
    private javax.swing.JTextField txtmap1;
    private javax.swing.JTextField txttang;
    private javax.swing.JTextField txttang1;
    // End of variables declaration//GEN-END:variables

    private dphong getbyform() {
    String ma=txtmap.getText();
    String maloai=(String) cboloaip.getSelectedItem();
    int dientich = Integer.parseInt(txtdientich.getText()) ;
    int tang = Integer.parseInt(txttang.getText());
    String hinh = "";
    int tinhtrang = Integer.parseInt((String) cbotinhtrang.getSelectedItem());
    String ghichu = txtghichu.getText();
    return new dphong(ma, maloai, dientich, tang, hinh, tinhtrang, ghichu);
    }

    
    
      
}
